/**
 * @typedef {Object} Store
 * @property {string} id
 * @property {string} name
 * @property {string} status
 * @property {string} province
 * @property {string} region
 * @property {Object} location
 * @property {string} location.address
 * @property {string} location.city
 * @property {string} location.postalCode
 * @property {Object} location.coordinates
 * @property {number} location.coordinates.lat
 * @property {number} location.coordinates.lng
 * @property {string} [location.market]
 * @property {string} [location.banner]
 * @property {string} [location.originalGoDate]
 * @property {string} [location.originalGoFY]
 * @property {string} [location.scGoDate]
 * @property {string} [location.scGoFY]
 * @property {string} [location.scType]
 * @property {number} [location.ageOfBox]
 * @property {string} [location.lastTouchProjectYear]
 * @property {string} [location.lastTouchType]
 * @property {string} [location.lastTouchStatus]
 * @property {string} [location.lastTouchGoDate]
 * @property {string} [location.template]
 * @property {number} [location.totalStoreSqft]
 * @property {string} [location.acquisitionHistory]
 * @property {boolean} [location.storeFormatBN]
 * @property {boolean} [location.storeFormatBCN]
 * @property {boolean} [location.storeFormatDiv1]
 * @property {boolean} [location.storeFormatSC]
 * @property {Object} building
 * @property {number} building.size
 * @property {number} building.floors
 * @property {number} building.yearBuilt
 * @property {number} building.lastRenovated
 * @property {string} [building.ownedVsLeased]
 * @property {boolean} [building.mallStore]
 * @property {number} [building.mallEntrances]
 * @property {number} [building.securityEntranceGates]
 * @property {string} [building.shoppingCentreType]
 * @property {string} [building.assetProtectionSecurityRoom]
 * @property {boolean} [building.hasBasement]
 * @property {boolean} [building.receivingOnDifferentFloor]
 * @property {boolean} [building.hasMezzanine]
 * @property {number} [building.freightElevators]
 * @property {string} [building.customerElevatorLocation]
 * @property {string} [building.verticalTransportation]
 * @property {boolean} [building.hasShoppingCartMovator]
 * @property {string} [building.cartCorral]
 * @property {Object} site
 * @property {number} site.parkingSpaces
 * @property {string[]} site.accessibility
 * @property {number} [site.accessibleSpaces]
 * @property {number} [site.expectingMotherSpaces]
 * @property {number} [site.greenParkingSpaces]
 * @property {number} [site.chargingStations]
 * @property {string} [site.cartCorralExterior]
 * @property {string} [site.parkingLocation]
 * @property {string} site.hoursOfOperation
 * @property {Object} salesFloor
 * @property {number} salesFloor.size
 * @property {string[]} salesFloor.departments
 * @property {number} salesFloor.checkoutCounters
 * @property {string} salesFloor.foodLocation
 * @property {string} salesFloor.flooring
 * @property {string} salesFloor.woodgrainType
 * @property {boolean} salesFloor.hasGardenCenter
 * @property {string} [salesFloor.gardenCenterType]
 * @property {boolean} salesFloor.hasHoseBib
 * @property {Object} food
 * @property {boolean} food.hasRestaurant
 * @property {boolean} food.hasBakery
 * @property {string} [food.bakeryLocation]
 * @property {boolean} food.hasDelicatessen
 * @property {boolean} [food.hasSushi]
 * @property {string} [food.sushiVendor]
 * @property {boolean} [food.hasServiceDeli]
 * @property {boolean} [food.hasDeliHMRScreens]
 * @property {string[]} food.specialtyFoods
 * @property {Object} pharmacy
 * @property {boolean} pharmacy.isPresent
 * @property {boolean} pharmacy.hasClinic
 * @property {string} [pharmacy.location]
 * @property {string} [pharmacy.tier]
 * @property {boolean} [pharmacy.hasSeating]
 * @property {number} [pharmacy.consultationRooms]
 * @property {string[]} pharmacy.services
 * @property {Object} marketing
 * @property {string[]} marketing.promotions
 * @property {string[]} marketing.specialEvents
 * @property {string} marketing.demographics
 * @property {boolean} [marketing.hasMinale]
 * @property {boolean} [marketing.hasEnchilada]
 * @property {boolean} [marketing.hasSwipeUp]
 * @property {boolean} [marketing.hasPreMinale]
 * @property {boolean} [marketing.hasLitFittingRoom]
 * @property {Object} backroom
 * @property {number} backroom.size
 * @property {boolean} backroom.hasLoadingDock
 * @property {number} [backroom.loadingDocks]
 * @property {number} [backroom.receivingAreas]
 * @property {string} [backroom.ceilingHeight]
 * @property {boolean} [backroom.hasMultiHeightCeiling]
 * @property {number} [backroom.highSteelPalletSpots]
 * @property {number} [backroom.cagesLockups]
 * @property {number} [backroom.cblTerminals]
 * @property {string} backroom.storageCapacity
 * @property {string[]} backroom.securityFeatures
 * @property {Object} [omni]
 * @property {number} omni.parkingSpaces
 * @property {string} omni.orangeBranding
 * @property {number} omni.directAccess
 * @property {number} omni.vanLoading
 * @property {boolean} omni.hasMobileCheckIn
 * @property {string} omni.mobileCheckInType
 */